server:
  port: 2024
spring:
  application:
    name: data-server-gateway
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.10.140:8848
    gateway:
      discovery:
        locator:
          enabled: true
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOriginPatterns: "*"
            # 允许请求中携带的头信息
            allowedHeaders: "*"
            # 运行跨域的请求方式
            allowedMethods: "*"
            # 跨域检测的有效期,单位s
            maxAge: 36000
      routes:
        - id: data-government
          uri: lb://data-government
          predicates:
            - Path=/government/**
        - id: data-manager
          uri: lb://data-manager
          predicates:
            - Path=/admin/*/**
        - id: data-report
          uri: lb://data-report
          predicates:
            - Path=/report/**
        - id: data-schedule
          uri: lb://data-schedule
          predicates:
            - Path=/schedule/**
        - id: data-statistics
          uri: lb://data-statistics
          predicates:
            - Path=/statistic/*/**
        - id: Swagger-All
          uri: lb://Swagger-All
          predicates:
            - Path=/swagger-resources/**


#        - id: "swagger-route"
#          uri: "lb://knife4j"
#          predicates:
#            - Path=/doc/**
#          filters:
#            - RewritePath=/doc/(?<segment>.*), /$\{segment}


#禁用自动配置的数据源
#  autoconfigure:
#    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

#Spring Boot使用响应式的Web应用程序类型，以与Spring Cloud Gateway(属于响应式)兼容
  main:
    web-application-type: reactive